Monitoring/Models/ErrorViewModel.cs
namespace Monitoring.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Monitoring/Models/ListUserPcViewModel.cs
namespace Monitoring.Models;

public class ListUserPcViewModel
{
    public string Id { get; set; }
    public string MachineName { get; set; }
    public string Os { get; set; }
}

Monitoring/Controllers/HardwareInfoController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Monitoring.Data;
using Monitoring.Data.Entity;

namespace Monitoring.Controllers;

[Route("/hardware")]
public class HardwareInfoController : ControllerBase
{
    private readonly ApplicationContext _context;

    public HardwareInfoController(ApplicationContext context)
    {
        _context = context;
    }

    [HttpPost]
    public async Task<IActionResult> CreateUserPc([FromBody] UserPc userPc)
    {
        _context.UserPcs.Add(userPc);
        await _context.SaveChangesAsync();
        return Ok(userPc.Id);
    }


    [HttpGet]
    public async Task<IActionResult> IsUserExist([FromQuery] string userPcId)
    {
        var user = await _context.UserPcs.FirstOrDefaultAsync(x => x.Id == userPcId);
        if (user == null)
        {
            return NotFound();
        }

        return Ok();
    }
}

Monitoring/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Monitoring.Data;
using Monitoring.Models;

namespace Monitoring.Controllers;

public class HomeController : Controller
{
    private readonly ApplicationContext _context;

    public HomeController(ApplicationContext context)
    {
        _context = context;
    }

    public IActionResult Index()
    {
        var listUserPcViewModels = _context.UserPcs.Include(x => x.Os).Select(x => new ListUserPcViewModel()
        {
            Id = x.Id,
            MachineName = x.Os.MachineName,
            Os = x.Os.Caption
        }).ToList();
        return View(listUserPcViewModels);
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Monitoring/Controllers/MonitoringController.cs
using HardWareMonitorService.Entity.Monitoring.ViewModel;
using Microsoft.AspNetCore.Mvc;

namespace Monitoring.Controllers;

public class MonitoringController : Controller
{
    public MonitoringController()
    {
    }

    public IActionResult Index(string id)
    {
        var userPcId = new UserPcIdViewModel()
        {
            UserPcId = id
        };
        return View(userPcId);
    }
}

Monitoring/Controllers/UserPcInfoController.cs
using Microsoft.AspNetCore.Components;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Monitoring.Data;

namespace Monitoring.Controllers;

public class UserPcInfoController : Controller
{
    private readonly ApplicationContext _context;

    public UserPcInfoController(ApplicationContext context)
    {
        _context = context;
    }

    public async Task<IActionResult> Index(string id)
    {
        var userInfo = await _context.UserPcs.Include(x => x.Os).Include(x => x.Cpu).Include(x => x.Gpu)
            .Include(x => x.Storages).Include(x => x.Rams).Include(x => x.MotherBoard).
            FirstOrDefaultAsync(x => x.Id == id);
        if (userInfo is null) return NotFound();
        
        return View(userInfo);
    }
}

Monitoring/Views/Home/Index.cshtml
@using Monitoring.Controllers
@model List<ListUserPcViewModel>
@{
    ViewData["Title"] = "Home Page";
}


<div class="text-center">
    <h1 class="display-4">Добро пожаловать</h1>
    <p>Здесь отображаются список подключенных ПК</p>
    <table class="table table-hover table-striped table-dark ">
        <thead>
        <tr>
            <th scope="col">MachineName</th>
            <th scope="col">Os</th>
            <th scope="col">Status</th>
            <th scope="col"></th>
        </tr>
        </thead>
        <tbody>
        @foreach (var item in Model)
        {
            <tr class="clickable-row" data-href="@Url.Action("Index", "UserPcInfo", new { id = item.Id })" data-userpcid="@item.Id">
                <td>@item.MachineName</td>
                <td>@item.Os</td>
                <td class="status">Оффлайн</td>
                <td>
                    <button class="btn-primary" data-href="@Url.Action("Index", "Monitoring", new { id = item.Id })">Monitoring</button>
                </td>
            </tr>
        }
        </tbody>
    </table>
</div>

@section Scripts

{<script src="https://cdnjs.cloudflare.com/ajax/libs/microsoft-signalr/3.1.18/signalr.min.js"></script>

    <script>
    const connection = new signalR.HubConnectionBuilder()
        .withUrl("/monitoring")
        .build();
    
    connection.on("UserOnline",(users)=>{
        console.log(users);
        for (let x of  users){
            console.log(x);
            const statusElement = document.querySelector(`[data-userpcid='${x}'] .status`);
            statusElement.textContent ="Онлайн";
        }
        });

    connection.on("UpdateStatus", (userPcId, isOnline) => {
        const statusElement = document.querySelector(`[data-userpcid='${userPcId}'] .status`);
        if (statusElement) {
            statusElement.textContent = isOnline ? "Онлайн" : "Оффлайн";
        }
    });

    connection.start().then(function () { connection.invoke("GetOnlineUser")}).catch(err => console.error(err.toString()));
    
</script>
    <script>
    $(document).ready(function() {
        $(".clickable-row").click(function() {
            window.location = $(this).data("href");
        });
        
        $(".clickable-row button").click(function(event) {
            event.stopPropagation();
            window.location = $(this).data("href");
        });
    });
    
</script> }

Monitoring/Views/Monitoring/Index.cshtml
@model HardWareMonitorService.Entity.Monitoring.ViewModel.UserPcIdViewModel


<h2>Real-Time Monitoring</h2>

<div>
    <h3>CPU</h3>
    <div style="display: flex; justify-content: space-between;">
        <div>
            <p>
                <strong>Total Load:</strong> <span id="cpuRtTotalLoad"></span>
            </p>
            <canvas id="cpuLoadChart" width="400" height="200"></canvas>
        </div>
        <div>
            <p>
                <strong>Temperature:</strong> <span id="cpuRtTemperature"></span>
            </p>
            <canvas id="cpuTempChart" width="400" height="200"></canvas>
        </div>
        <div>
            <p>
                <strong>Voltage:</strong> <span id="cpuRtVoltage"></span>
            </p>
            <canvas id="cpuVoltageChart" width="400" height="200"></canvas>
        </div>
    </div>
</div>

<div>
    <h3>GPU</h3>
    <div style="display: flex; justify-content: space-between;">
        <div>
            <p>
                <strong>Total Load:</strong> <span id="gpuRtTotalLoad"></span>
            </p>
            <canvas id="gpuLoadChart" width="400" height="200"></canvas>
        </div>
        <div>
            <p>
                <strong>Temperature:</strong> <span id="gpuRtTemperature"></span>
            </p>
            <canvas id="gpuTempChart" width="400" height="200"></canvas>
        </div>
        <div>
            <p>
                <strong>Fan Speed:</strong> <span id="gpuRtFan"></span>
            </p>
            <canvas id="gpuFanChart" width="400" height="200"></canvas>
        </div>
    </div>
</div>

<div>
    <h3>Network</h3>
    <div style="display: flex; justify-content: flex-start;">
        <div>
            <p>
                <strong>Download:</strong> <span id="networkRtDownload"></span>
            </p>
            <canvas id="networkDownloadChart" width="400" height="200"></canvas>
        </div>
        <div>
            <p>
                <strong>Upload:</strong> <span id="networkRtUpload"></span>
            </p>
            <canvas id="networkUploadChart" width="400" height="200"></canvas>
        </div>
    </div>
</div>

<div>
    <h3>RAM</h3>
    <div style="display: flex; justify-content: space-between;">
        <div>
            <p>
                <strong>Used:</strong> <span id="ramRtUsed"></span>
            </p>
            <canvas id="ramUsedChart" width="400" height="200"></canvas>
        </div>
        <div>
            <p>
                <strong>Available:</strong> <span id="ramRtAvailable"></span>
            </p>
            <canvas id="ramAvailableChart" width="400" height="200"></canvas>
        </div>
        <div>
            <p>
                <strong>Load:</strong> <span id="ramRtLoad"></span>
            </p>
            <canvas id="ramLoadChart" width="400" height="200"></canvas>
        </div>
    </div>
</div>

@section Scripts {
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.4/Chart.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/microsoft-signalr/3.1.12/signalr.min.js"></script>
    <script type="text/javascript">
    $(document).ready(function () {
        const chartWidth = 400;
        const chartHeight = 200;
        const connection = new signalR.HubConnectionBuilder().withUrl("/monitoring").build();

        window.onbeforeunload = function () {
            connection.invoke("StopMonitoring","@Model.UserPcId")
        };

        const createChart = (ctx, yMin, yMax,step) => {
            return new Chart(ctx, {
                type: 'line',
                data: {
                    labels: [], // метки времени или индексы
                    datasets: [{
                        label: 'Value',
                        data: [],
                        borderColor: 'rgba(75, 192, 192, 1)',
                        borderWidth: 1,
                        fill: false
                    }]
                },
                options: {
                    scales: {
                        xAxes: {
                            type: 'linear',
                            position: 'bottom'
                        },
                        yAxes: [{
                            ticks: {
                                min: yMin,
                                max: yMax,
                                stepSize: step,
                                beginAtZero: true,
                                suggestedMin: yMin,
                                suggestedMax: yMax
                            }
                        }]
                    }
                }
            });
        };
        
        const cpuLoadChart = createChart(document.getElementById('cpuLoadChart').getContext('2d'), 0, 100,20 );
        const cpuTempChart = createChart(document.getElementById('cpuTempChart').getContext('2d'), 0, 100,20);
        const cpuVoltageChart = createChart(document.getElementById('cpuVoltageChart').getContext('2d'), 0, 2, 0.01);
        const gpuLoadChart = createChart(document.getElementById('gpuLoadChart').getContext('2d'), 0, 100, 20);
        const gpuTempChart = createChart(document.getElementById('gpuTempChart').getContext('2d'), 0, 100, 20);
        const gpuFanChart = createChart(document.getElementById('gpuFanChart').getContext('2d'), 0, 5000, 1250);
        const networkDownloadChart = createChart(document.getElementById('networkDownloadChart').getContext('2d'), 0, 65, 15);
        const networkUploadChart = createChart(document.getElementById('networkUploadChart').getContext('2d'), 0, 100, 20);
        const ramUsedChart = createChart(document.getElementById('ramUsedChart').getContext('2d'), 0, 32, 8);
        const ramAvailableChart = createChart(document.getElementById('ramAvailableChart').getContext('2d'), 0, 32, 8);
        const ramLoadChart = createChart(document.getElementById('ramLoadChart').getContext('2d'), 0, 100, 20);




        const updateChart = (chart, label, data) => {
            chart.data.labels.push(label);
            chart.data.datasets[0].data.push(data);
            if (chart.data.labels.length > 10) { // Максимальное количество точек на графике
                chart.data.labels.shift();
                chart.data.datasets[0].data.shift();
            }
            chart.update();
        };
        
        connection.on("ReceiveMonitoringInfo", function (pcMonitoringInfo) {
            const timeLabel = new Date().toLocaleTimeString();

            $('#cpuRtTotalLoad').text(pcMonitoringInfo.cpuRt.totalLoad + " %");
            $('#cpuRtTemperature').text(pcMonitoringInfo.cpuRt.temperature + " ℃");
            $('#cpuRtVoltage').text(pcMonitoringInfo.cpuRt.voltage + " V");
            updateChart(cpuLoadChart, timeLabel, pcMonitoringInfo.cpuRt.totalLoad);
            updateChart(cpuTempChart, timeLabel, pcMonitoringInfo.cpuRt.temperature);
            updateChart(cpuVoltageChart, timeLabel, pcMonitoringInfo.cpuRt.voltage);

            $('#gpuRtTotalLoad').text(pcMonitoringInfo.gpuRt.totalLoad + " %");
            $('#gpuRtTemperature').text(pcMonitoringInfo.gpuRt.temperature + " ℃");
            $('#gpuRtFan').text(pcMonitoringInfo.gpuRt.fan + " RPM");
            updateChart(gpuLoadChart, timeLabel, pcMonitoringInfo.gpuRt.totalLoad);
            updateChart(gpuTempChart, timeLabel, pcMonitoringInfo.gpuRt.temperature);
            updateChart(gpuFanChart, timeLabel, pcMonitoringInfo.gpuRt.fan);

            $('#networkRtDownload').text(pcMonitoringInfo.networkRt.download + " Mb");
            $('#networkRtUpload').text(pcMonitoringInfo.networkRt.upload + " Mb");
            updateChart(networkDownloadChart, timeLabel, pcMonitoringInfo.networkRt.download);
            updateChart(networkUploadChart, timeLabel, pcMonitoringInfo.networkRt.upload);

            $('#ramRtUsed').text(pcMonitoringInfo.ramRt.used + " Gb");
            $('#ramRtAvailable').text(pcMonitoringInfo.ramRt.available + " Gb");
            $('#ramRtLoad').text(pcMonitoringInfo.ramRt.load + " %");
            updateChart(ramUsedChart, timeLabel, pcMonitoringInfo.ramRt.used);
            updateChart(ramAvailableChart, timeLabel, pcMonitoringInfo.ramRt.available);
            updateChart(ramLoadChart, timeLabel, pcMonitoringInfo.ramRt.load);
        });
        
        connection.start().then(function () {
            connection.invoke("StartMonitoring","@Model.UserPcId")
            console.log("SignalR connected.");
        }).catch(function (err) {
            return console.error(err.toString());
        });
    });

    
    </script>
}

Monitoring/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en" >
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - Monitoring</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/Monitoring.styles.css" asp-append-version="true"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Monitoring</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2024 - Monitoring - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>

@await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Monitoring/Views/UserPcInfo/Index.cshtml
@model Monitoring.Data.Entity.UserPc

<div class="container">
    <h2>Details</h2>

    <!-- CPU Section -->
    <div class="row">
        <div class="col-md-6">
            <div class="card mb-3">
                <div class="card-header">
                    CPU:
                </div>
                <div class="card-body">
                    <p>
                        <strong>Name:</strong> @Model.Cpu.Name
                    </p>
                    <p>
                        <strong>Cores:</strong> @Model.Cpu.Cores
                    </p>
                    <p>
                        <strong>Threads:</strong> @Model.Cpu.Threads
                    </p>
                    <p>
                        <strong>Frequency:</strong> @Model.Cpu.Freq
                    </p>
                    <p>
                        <strong>Socket:</strong> @Model.Cpu.Socket
                    </p>
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="card mb-3">
                <div class="card-header">
                    Motherboard:
                </div>
                <div class="card-body">
                    <p>
                        <strong>Name:</strong> @Model.MotherBoard.Name
                    </p>
                </div>
            </div>
        </div>
    </div>


    <div class="row">
        <div class="col-md-6">
            <!-- GPU Section -->
            <div class="card mb-3">
                <div class="card-header">
                    GPU:
                </div>
                <div class="card-body">
                    <p>
                        <strong>Name:</strong> @Model.Gpu.Name
                    </p>
                    <p>
                        <strong>Adapter Ram:</strong> @Model.Gpu.AdapterRam
                    </p>
                    <p>
                        <strong>Driver:</strong> @Model.Gpu.Driver
                    </p>
                </div>
            </div>
        </div>


        <!-- OS Section -->
        <div class="col-md-6">
            <div class="card mb-3">
                <div class="card-header">
                    OS:
                </div>
                <div class="card-body">
                    <p>
                        <strong>Caption:</strong> @Model.Os.Caption
                    </p>
                    <p>
                        <strong>Build:</strong> @Model.Os.Build
                    </p>
                    <p>
                        <strong>Architecture:</strong> @Model.Os.OsArchitecture
                    </p>
                    <p>
                        <strong>Machine Name:</strong> @Model.Os.MachineName
                    </p>
                </div>
            </div>
        </div>
    </div>


    <!-- RAM Section -->
    <div class="row">
        <div class="col-md-6">
            <div class="card mb-3">
                <div class="card-header">
                    RAM:
                </div>
                @foreach (var ram in Model.Rams)
                {
                    <div class="card-body">
                        <p>
                            <strong>Name:</strong> @ram.Name
                        </p>
                        <p>
                            <strong>Speed:</strong> @ram.Speed
                        </p>
                        <p>
                            <strong>Capacity:</strong> @ram.Capacity
                        </p>
                    </div>
                }
            </div>
        </div>


        <!-- Storage Section -->
        <div class="col-md-6">
            <div class="card mb-3">
                <div class="card-header">
                    Storage:
                </div>
                @foreach (var storage in Model.Storages)
                {
                    <div class="card-body">
                        <p>
                            <strong>Name:</strong> @storage.Name
                        </p>
                        <p>
                            <strong>Total Size:</strong> @storage.TotalSize
                        </p>
                    </div>
                }
            </div>
        </div>
    </div>


</div>